### ISSUE TITLE
GPU Miner 

### ISSUE THREAD

**Issue by ghost** [geedo0/cuda_bitcoin_miner#1]
Hi Gerardo,
How does the GPU miner differ from CPU miner? What part of the code needs to be changed or optimized to enable GPU mining? 
Thank you.
Michael

**Comment by geedo0** [comment]
The GPU and CPU miners differ considerably since they target two very different processor architecture. To port the CPU miner over to the GPU I converted the sequential algorithm over to a SIMT execution model. Basically, this amounted to converting the individual loop iterations to SIMT threads to be executed on the GPU. From there it was a matter of optimizing the CUDA kernel code to take advantage of every bit of hardware acceleration available on the particular GPU I was targeting. For details on this checkout the pdf in the repository.
